name: e_shop
description:

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^0.6.0
  animated_text_kit: ^2.4.1
  google_fonts: ^1.1.1
  drawing_animation: ^0.1.3
#  cupertino_icons: ^0.1.3
#  cloud_firestore: ^0.13.2+1
#  firebase_auth: ^0.15.4
  shared_preferences: ^0.5.6+1
  fluttertoast: ^3.1.3
  image_picker: ^0.6.3+1
  firebase_storage: ^3.1.1
  flutter_staggered_grid_view: ^0.3.0
  provider: ^4.0.4
  flutter_icons: ^1.1.0
  cupertino_icons: ^1.0.0
  firebase_database: ^3.1.3
  form_field_validator: ^1.0.1
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.5
  google_sign_in: ^4.4.4
  cloud_firestore: ^0.13.7
  firebase_analytics: ^5.0.2

  path_provider: ^1.4.0
  image: ^2.0.7

  flutter_svg: ^0.19.1
  intl:


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

  assets:
    - assets/
    - images/


